name: Build 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Create Output Directory
        run: mkdir -p cli

      - name: Build Executable
        run: go build -o cli/hanzicli cli.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-executable
          path: cli/
